
site_name: Guide for CWL in Earth Observation

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: 'docs/'

nav:
  - Introduction: 'index.md'
  - What you need to know:
    - About this sections: 101/about.md
    - Containers 101: '101/containers.md'
    - YAML 101: '101/yaml.md'
    - CWL 101: '101/cwl.md'
  - Requirements: requirements.md
  - EO toolboxes:
    - SNAP:
      - SNAP 101: '101/snap.md'
      - Run SNAP graphs with CWL: 'cwl-snap-graph-runner/README.md'
    - OrfeoToolbox:
      - Orfeo Toolbox 101: '101/orfeo-toolbox.md'
      - BandMathX: otb/bandmathx/README.md
      - BundleToPerfectSensor: otb/landsat-8-pan-sharpening/README.md
      - Mosaic: otb/landsat-8-mosaic/README.md
  - EO tools:
    - GDAL:
      - GDAL 101: '101/gdal.md'
      - gdal_translate: gdal/gdal_translate/README.md
  - Python:
    - Introduction: python/introduction.md
  - STAC:
    - Introduction: stac/README.md
    - Sentinel-2 asset resolution: stac/sentinel-2-asset-resolution/README.md
  - EO Workflows:
    - Sentinel-2 NBR: workflows/sentinel-2-nbr/README.md
    - Landsat-8 pan-sharpening: otb/landsat-8-pan-sharpening/README.md
    - Landsat-8 mosaic: otb/landsat-8-mosaic/README.md
