
site_name: Guide for CWL in Earth Observation

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Introduction: 'index.md'
  - EO toolboxes:
    - SNAP:
      - Run SNAP graphs with CWL: 'cwl-snap-graph-runner/README.md'
