
site_name: Guide for CWL in Earth Observation

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - def_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.snippets:
      base_path: 'docs/'

plugins:
  - search
  - mermaid2

extra_css:
  - https://unpkg.com/mermaid@8.8.0/dist/mermaid.css
  
extra_javascript:
  - https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js


nav:
  - Introduction: 'index.md'
  - Requirements: requirements.md
  - What you need to know:
    - Containers 101: '101/containers.md'
    - YAML 101: '101/yaml.md'
    - CWL 101: '101/cwl-101/cwl.md'
  - Tutorials:
    - Your first CommandLineTool: '101/cwl-101/command-line-tool.md'
    - Your first Worflow: '101/cwl-101/workflow.md'
    - SNAP:
      - SNAP with CWL: 'snap/snap-cwl/snap-cwl.md'
      - SNAP Graph as File: 'snap/snap-cwl/graph-as-a-file.md'
      - SNAP Graph inline: 'snap/snap-cwl/graph-inline.md'
    - OrfeoToolbox:
      - Orfeo Toolbox 101: '101/orfeo-toolbox.md'
      - BandMathX: otb/bandmathx/README.md
      - BundleToPerfectSensor: otb/landsat-8-pan-sharpening/README.md
      - Mosaic: otb/landsat-8-mosaic/README.md 
    - GDAL:
      - GDAL 101: '101/gdal.md'
      - gdal_translate: gdal/gdal_translate/README.md
    - STAC: 
      - Introduction: stac/README.md
      - Sentinel-2 asset resolution: stac/sentinel-2-asset-resolution/README.md
  - How-to:
    - CWL: 
      - How to return an output file: how-to/cwl-how-to/return-output-file.md
      - How to capture the stdout: how-to/cwl-how-to/capture-stdout.md
      - How to capture JSON stdout and re-use it: how-to/cwl-how-to/capture-json-stdout.md
      - How to set environment variables: how-to/cwl-how-to/environment-variables.md
      - How to scatter workflows: how-to/cwl-how-to/scatter-workflows.md
      - How to scatter on input parameters: how-to/cwl-how-to/scatter-input-parameters.md
      - How to create nested workflows: how-to/cwl-how-to/nested-workflow.md
      - How to create conditional workflows: how-to/cwl-how-to/conditional-workflows.md
    - Sentinel-2:
      - Sentinel-2 NBR: workflows/sentinel-2-nbr/README.md
    - Landsat-8:
      - Pan-sharpening with OTB: otb/landsat-8-pan-sharpening/README.md
      - True color mosaic: otb/landsat-8-mosaic/README.md
  - Reference:
    - CWL Command Line Tool Description: reference/cwl-clt.md
    - CWL Workflow Description: reference/cwl-workflow.md
  - Explanation:
    - SNAP: snap/101.md
