
site_name: Guide for CWL in Earth Observation

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - def_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.snippets:
      base_path: 'docs/'

plugins:
  - search
  - mermaid2

extra_css:
  - https://unpkg.com/mermaid@8.8.0/dist/mermaid.css
  
extra_javascript:
  - https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js


nav:
  - Introduction: 'index.md'
  - What you need to know:
    - About this section: 101/about.md
    - Containers 101: '101/containers.md'
    - YAML 101: '101/yaml.md'
    - CWL 101: '101/cwl.md'
  - Requirements: requirements.md
  - EO toolboxes:
    - SNAP:
      - SNAP 101: 'snap/101.md'
      - SNAP with CWL: 'snap/snap-cwl/snap-cwl.md'
      - Run SNAP graphs with CWL: 'cwl-snap-graph-runner/README.md'
    - OrfeoToolbox:
      - Orfeo Toolbox 101: '101/orfeo-toolbox.md'
      - BandMathX: otb/bandmathx/README.md
      - BundleToPerfectSensor: otb/landsat-8-pan-sharpening/README.md
      - Mosaic: otb/landsat-8-mosaic/README.md
  - EO tools:
    - GDAL:
      - GDAL 101: '101/gdal.md'
      - gdal_translate: gdal/gdal_translate/README.md
  - Python:
    - Introduction: python/introduction.md
  - STAC:
    - Introduction: stac/README.md
    - Sentinel-2 asset resolution: stac/sentinel-2-asset-resolution/README.md
  - EO Workflows:
    - Sentinel-2 NBR: workflows/sentinel-2-nbr/README.md
    - Landsat-8 pan-sharpening: otb/landsat-8-pan-sharpening/README.md
    - Landsat-8 mosaic: otb/landsat-8-mosaic/README.md
