
site_name: Guide for CWL in Earth Observation

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Introduction: 'index.md'
  - What you need to know:
    - About this sections: 101/about.md
    - Containers 101: '101/containers.md'
    - YAML 101: '101/yaml.md'
    - CWL 101: '101/cwl.md'
  - Requirements: requirements.md
  - EO toolboxes:
    - SNAP:
      - SNAP 101: '101/snap.md'
      - Run SNAP graphs with CWL: 'cwl-snap-graph-runner/README.md'
    - OrfeoToolbox:
      - Orfeo Toolbox 101: '101/orfeo-toolbox.md'
  - EO tools:
    - GDAL:
      - GDAL 101: '101/gdal.md'
  - Python:
    - Introduction: python/introduction.md
  - STAC:
    - Introduction: stac/README.md
    - Sentinel-2 asset resolution: stac/sentinel-2-asset-resolution/README.md