
site_name: cwl-for-eo

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Introduction: 'index.md'
  - Run SNAP graphs with CWL: 'cwl-snap-graph-runner/README.md'
